/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard.projects.$projectId'
import { Route as DashboardProjectsProjectIdIndexRouteImport } from './routes/dashboard.projects.$projectId.index'
import { Route as DashboardProjectsProjectIdUsageRouteImport } from './routes/dashboard.projects.$projectId.usage'
import { Route as DashboardProjectsProjectIdSetupRouteImport } from './routes/dashboard.projects.$projectId.setup'
import { Route as DashboardProjectsProjectIdSettingsRouteImport } from './routes/dashboard.projects.$projectId.settings'
import { Route as DashboardProjectsProjectIdRecordsRouteImport } from './routes/dashboard.projects.$projectId.records'
import { Route as DashboardProjectsProjectIdLogsRouteImport } from './routes/dashboard.projects.$projectId.logs'
import { Route as DashboardProjectsProjectIdKeysRouteImport } from './routes/dashboard.projects.$projectId.keys'
import { Route as DashboardProjectsProjectIdEventsRouteImport } from './routes/dashboard.projects.$projectId.events'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdUsageRoute =
  DashboardProjectsProjectIdUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdSetupRoute =
  DashboardProjectsProjectIdSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdSettingsRoute =
  DashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdRecordsRoute =
  DashboardProjectsProjectIdRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdLogsRoute =
  DashboardProjectsProjectIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdKeysRoute =
  DashboardProjectsProjectIdKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdEventsRoute =
  DashboardProjectsProjectIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/$projectId/events': typeof DashboardProjectsProjectIdEventsRoute
  '/dashboard/projects/$projectId/keys': typeof DashboardProjectsProjectIdKeysRoute
  '/dashboard/projects/$projectId/logs': typeof DashboardProjectsProjectIdLogsRoute
  '/dashboard/projects/$projectId/records': typeof DashboardProjectsProjectIdRecordsRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/setup': typeof DashboardProjectsProjectIdSetupRoute
  '/dashboard/projects/$projectId/usage': typeof DashboardProjectsProjectIdUsageRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId/events': typeof DashboardProjectsProjectIdEventsRoute
  '/dashboard/projects/$projectId/keys': typeof DashboardProjectsProjectIdKeysRoute
  '/dashboard/projects/$projectId/logs': typeof DashboardProjectsProjectIdLogsRoute
  '/dashboard/projects/$projectId/records': typeof DashboardProjectsProjectIdRecordsRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/setup': typeof DashboardProjectsProjectIdSetupRoute
  '/dashboard/projects/$projectId/usage': typeof DashboardProjectsProjectIdUsageRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/$projectId/events': typeof DashboardProjectsProjectIdEventsRoute
  '/dashboard/projects/$projectId/keys': typeof DashboardProjectsProjectIdKeysRoute
  '/dashboard/projects/$projectId/logs': typeof DashboardProjectsProjectIdLogsRoute
  '/dashboard/projects/$projectId/records': typeof DashboardProjectsProjectIdRecordsRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/setup': typeof DashboardProjectsProjectIdSetupRoute
  '/dashboard/projects/$projectId/usage': typeof DashboardProjectsProjectIdUsageRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/$projectId/events'
    | '/dashboard/projects/$projectId/keys'
    | '/dashboard/projects/$projectId/logs'
    | '/dashboard/projects/$projectId/records'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/setup'
    | '/dashboard/projects/$projectId/usage'
    | '/dashboard/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/dashboard'
    | '/dashboard/projects/$projectId/events'
    | '/dashboard/projects/$projectId/keys'
    | '/dashboard/projects/$projectId/logs'
    | '/dashboard/projects/$projectId/records'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/setup'
    | '/dashboard/projects/$projectId/usage'
    | '/dashboard/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/$projectId/events'
    | '/dashboard/projects/$projectId/keys'
    | '/dashboard/projects/$projectId/logs'
    | '/dashboard/projects/$projectId/records'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/setup'
    | '/dashboard/projects/$projectId/usage'
    | '/dashboard/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId/': {
      id: '/dashboard/projects/$projectId/'
      path: '/'
      fullPath: '/dashboard/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/usage': {
      id: '/dashboard/projects/$projectId/usage'
      path: '/usage'
      fullPath: '/dashboard/projects/$projectId/usage'
      preLoaderRoute: typeof DashboardProjectsProjectIdUsageRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/setup': {
      id: '/dashboard/projects/$projectId/setup'
      path: '/setup'
      fullPath: '/dashboard/projects/$projectId/setup'
      preLoaderRoute: typeof DashboardProjectsProjectIdSetupRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/settings': {
      id: '/dashboard/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/dashboard/projects/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/records': {
      id: '/dashboard/projects/$projectId/records'
      path: '/records'
      fullPath: '/dashboard/projects/$projectId/records'
      preLoaderRoute: typeof DashboardProjectsProjectIdRecordsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/logs': {
      id: '/dashboard/projects/$projectId/logs'
      path: '/logs'
      fullPath: '/dashboard/projects/$projectId/logs'
      preLoaderRoute: typeof DashboardProjectsProjectIdLogsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/keys': {
      id: '/dashboard/projects/$projectId/keys'
      path: '/keys'
      fullPath: '/dashboard/projects/$projectId/keys'
      preLoaderRoute: typeof DashboardProjectsProjectIdKeysRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/events': {
      id: '/dashboard/projects/$projectId/events'
      path: '/events'
      fullPath: '/dashboard/projects/$projectId/events'
      preLoaderRoute: typeof DashboardProjectsProjectIdEventsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
  }
}

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdEventsRoute: typeof DashboardProjectsProjectIdEventsRoute
  DashboardProjectsProjectIdKeysRoute: typeof DashboardProjectsProjectIdKeysRoute
  DashboardProjectsProjectIdLogsRoute: typeof DashboardProjectsProjectIdLogsRoute
  DashboardProjectsProjectIdRecordsRoute: typeof DashboardProjectsProjectIdRecordsRoute
  DashboardProjectsProjectIdSettingsRoute: typeof DashboardProjectsProjectIdSettingsRoute
  DashboardProjectsProjectIdSetupRoute: typeof DashboardProjectsProjectIdSetupRoute
  DashboardProjectsProjectIdUsageRoute: typeof DashboardProjectsProjectIdUsageRoute
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdEventsRoute:
      DashboardProjectsProjectIdEventsRoute,
    DashboardProjectsProjectIdKeysRoute: DashboardProjectsProjectIdKeysRoute,
    DashboardProjectsProjectIdLogsRoute: DashboardProjectsProjectIdLogsRoute,
    DashboardProjectsProjectIdRecordsRoute:
      DashboardProjectsProjectIdRecordsRoute,
    DashboardProjectsProjectIdSettingsRoute:
      DashboardProjectsProjectIdSettingsRoute,
    DashboardProjectsProjectIdSetupRoute: DashboardProjectsProjectIdSetupRoute,
    DashboardProjectsProjectIdUsageRoute: DashboardProjectsProjectIdUsageRoute,
    DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
